require 'nokogiri'
require 'open-uri'
require 'optparse'
require 'colorize'
require_relative '../lib/standings_scraper'
require_relative '../lib/standings'
require_relative '../lib/scores_scraper'
require_relative '../lib/scores'